# Generated by Django 4.2.27 on 2025-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
